[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AP-OOD"
version = "1.0.0"
dependencies = [
    "torch>=2.8.0",
    "numpy",
]

[tool.setuptools.packages.find]
where = ["../src"]  # Look inside the 'src' folder
include = ["ap_ood*", "ap_ood_experiments*"]  # Include this package
namespaces = false  # Set to true if using namespace packages
